### ISSUE TITLE
Empty folders fail to compress

### ISSUE THREAD

**Issue by larsnaesbye** [deic-dk/files_compress#14]
If a folder is empty, compression fails with the standard error.

**Comment by larsnaesbye** [comment]
This is not only if you're trying to compress an empty folder, it also excludes nested empty folders. Not good.

**Comment by kaspersort** [comment]
compress.php is now able to compress empty nested folders. Zip archiving utility has changed from Phar to ZipArchive.

**Comment by kaspersort** [comment]
Due to PHP ZipArchive limitations - file size max 4GB - we are now using the ordinary zip-command from the operating system.

**Comment by kaspersort** [comment]
compress.php is now able to compress empty directories. Case closed.
